config:
  credentials:
  - id: https://gitlab.com/PalomoIFCA/privategitlabtesting
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/PalomoIFCA/privategitlabtesting:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.com/PalomoIFCA/privategitlabtesting
      repo: https://gitlab.com/PalomoIFCA/privategitlabtesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting git:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_reckless_squirrel.sh
        container: qc.acc_echelon_cheerful_dugong
  QC.Doc:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_imaginative_otter.sh
        container: qc.doc_sunset_kind_crane
      gitlab.com/PalomoIFCA/privategitlabtesting git:
        commands:
        - /usr/bin/env sh .sqa/script.aqua_compassionate_albatross.sh
        container: qc.doc_gray_humble_boa
      gitlab.com/PalomoIFCA/privategitlabtesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grape_balanced_hedgehog.sh
        container: qc.doc_white_philosophical_camel
  QC.Lic:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_courageous_platypus.sh
        container: qc.lic_flax_rugged_elephant
  QC.Sec:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slate_driven_fox.sh
        container: qc.sec_teal_thankful_hippopotamus
  QC.Sty:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cobalt_scrappy_lynx.sh
        container: qc.sty_tundra_reserved_coyote
      gitlab.com/PalomoIFCA/privategitlabtesting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_stoic_panther.sh
        container: qc.sty_harlequin_polite_warthog
  QC.Uni:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goldenrod_humorous_dingo.sh
        container: qc.uni_pistachio_fierce_wolf
  QC.Ver:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flint_dizzy_osprey.sh
        container: qc.ver_mango_driven_baboon
timeout: 5400
