config:
  credentials:
  - id: https://gitlab.com/PalomoIFCA/privategitlabtesting
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/PalomoIFCA/privategitlabtesting:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.com/PalomoIFCA/privategitlabtesting
      repo: https://gitlab.com/PalomoIFCA/privategitlabtesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting git:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_resourceful_otter.sh
        container: qc.acc_dawn_eccentric_kiwi
  QC.Doc:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.salmon_mature_moose.sh
        container: qc.doc_nutmeg_thankful_hydra
      gitlab.com/PalomoIFCA/privategitlabtesting git:
        commands:
        - /usr/bin/env sh .sqa/script.umber_brilliant_tortoise.sh
        container: qc.doc_lilac_eager_condor
      gitlab.com/PalomoIFCA/privategitlabtesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_nurturing_elk.sh
        container: qc.doc_ginger_tough_dhole
  QC.Lic:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gray_rational_dragonfly.sh
        container: qc.lic_mint_stubborn_angelfish
  QC.Sec:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.magenta_supportive_flounder.sh
        container: qc.sec_bone_honest_nighthawk
  QC.Sty:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.salmon_enigmatic_osprey.sh
        container: qc.sty_kiwi_eager_beaver
      gitlab.com/PalomoIFCA/privategitlabtesting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flamingo_perky_manta.sh
        container: qc.sty_lilac_organized_sloth
  QC.Uni:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ivory_foolish_unicorn.sh
        container: qc.uni_amaranth_bold_koala
  QC.Ver:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chestnut_fierce_caribou.sh
        container: qc.ver_byzantium_observant_gecko
timeout: 5400
