config:
  credentials:
  - id: https://gitlab.com/PalomoIFCA/privategitlabtesting
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/PalomoIFCA/privategitlabtesting:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.com/PalomoIFCA/privategitlabtesting
      repo: https://gitlab.com/PalomoIFCA/privategitlabtesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting git:
        commands:
        - /usr/bin/env sh .sqa/script.green_courageous_boar.sh
        container: qc.acc_kiwi_generous_vulture
  QC.Doc:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jade_dizzy_pegasus.sh
        container: qc.doc_yellow_studious_bison
      gitlab.com/PalomoIFCA/privategitlabtesting git:
        commands:
        - /usr/bin/env sh .sqa/script.pineapple_dreamy_flounder.sh
        container: qc.doc_obsidian_sarcastic_badger
      gitlab.com/PalomoIFCA/privategitlabtesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.eggplant_eccentric_flamingo.sh
        container: qc.doc_ginger_carefree_sloth
  QC.Lic:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.periwinkle_diligent_falcon.sh
        container: qc.lic_cream_responsible_crocodile
  QC.Sec:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.kiwi_audacious_osprey.sh
        container: qc.sec_onyx_radiant_octopus
  QC.Sty:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pine_mysterious_sparrow.sh
        container: qc.sty_rose_dizzy_clownfish
      gitlab.com/PalomoIFCA/privategitlabtesting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cosmos_tough_chipmunk.sh
        container: qc.sty_yellow_shrewd_manatee
  QC.Uni:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_sweet_gorilla.sh
        container: qc.uni_nutmeg_fair_lynx
  QC.Ver:
    repos:
      gitlab.com/PalomoIFCA/privategitlabtesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.rust_passionate_hydra.sh
        container: qc.ver_cobalt_sarcastic_lynx
timeout: 5400
